services:
  - type: web
    plan: free
    name: docs-clone-client
    runtime: static
    rootDir: client
    buildFilter:
      paths:
        - client/**/*.jsx
    buildCommand: npm run build
    startCommand: npm run preview
  - type: web
    plan: free
    name: docs-clone-server
    runtime: node
    rootDir: server
    buildFilter:
      paths:
        - server/**/*.jsx
    buildCommand: npm i
    startCommand: node server.js
