services:
  - type: web
    name: docs-clone-client
    runtime: static
    rootDir: client
    buildCommand: npm i; npm run build
    staticPublishPath: ./client/build/
    buildFilter:
      paths:
        - client/**/*.jsx
  - type: web
    plan: free
    name: docs-clone-server
    runtime: node
    rootDir: server
    buildFilter:
      paths:
        - server/**/*.jsx
    buildCommand: npm i
    startCommand: node server.js
